package com.yuki.decmarket.mapper;

import com.yuki.decmarket.model.Favlists;
import com.yuki.decmarket.model.FavlistsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavlistsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int countByExample(FavlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int deleteByExample(FavlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int insert(Favlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int insertSelective(Favlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    List<Favlists> selectByExample(FavlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    Favlists selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") Favlists record, @Param("example") FavlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int updateByExample(@Param("record") Favlists record, @Param("example") FavlistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int updateByPrimaryKeySelective(Favlists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favlists
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int updateByPrimaryKey(Favlists record);

    List<Favlists> getFavListByUserID(int user_id);

    int findFavListByID(int user_id, int good_id);
}