package com.yuki.decmarket.mapper;

import com.yuki.decmarket.model.GoodsTags;
import com.yuki.decmarket.model.GoodsTagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int countByExample(GoodsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int deleteByExample(GoodsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int insert(GoodsTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int insertSelective(GoodsTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    List<GoodsTags> selectByExample(GoodsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    GoodsTags selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") GoodsTags record, @Param("example") GoodsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int updateByExample(@Param("record") GoodsTags record, @Param("example") GoodsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_tags
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    int updateByPrimaryKey(GoodsTags record);
}