package com.yuki.decmarket.model;

import java.util.Date;

public class Favlists {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favlists.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favlists.user_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favlists.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favlists.seller_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favlists.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favlists.id
     *
     * @return the value of favlists.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favlists.id
     *
     * @param id the value for favlists.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favlists.user_id
     *
     * @return the value of favlists.user_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favlists.user_id
     *
     * @param userId the value for favlists.user_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favlists.good_id
     *
     * @return the value of favlists.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favlists.good_id
     *
     * @param goodId the value for favlists.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favlists.seller_id
     *
     * @return the value of favlists.seller_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favlists.seller_id
     *
     * @param sellerId the value for favlists.seller_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favlists.created_at
     *
     * @return the value of favlists.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favlists.created_at
     *
     * @param createdAt the value for favlists.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}