package com.yuki.decmarket.model;

import java.util.Date;

public class GoodsTags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tags.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tags.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tags.tag_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_tags.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tags.id
     *
     * @return the value of goods_tags.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tags.id
     *
     * @param id the value for goods_tags.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tags.good_id
     *
     * @return the value of goods_tags.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tags.good_id
     *
     * @param goodId the value for goods_tags.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tags.tag_id
     *
     * @return the value of goods_tags.tag_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tags.tag_id
     *
     * @param tagId the value for goods_tags.tag_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_tags.created_at
     *
     * @return the value of goods_tags.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_tags.created_at
     *
     * @param createdAt the value for goods_tags.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}