package com.yuki.decmarket.model;

import java.util.Date;

public class Tags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.created_at
     *
     * @return the value of tags.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.created_at
     *
     * @param createdAt the value for tags.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}