package com.yuki.decmarket.model;

import java.util.Date;

public class Transactions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.buyer_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.number
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.status
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.reason
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.id
     *
     * @return the value of transactions.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.id
     *
     * @param id the value for transactions.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.good_id
     *
     * @return the value of transactions.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.good_id
     *
     * @param goodId the value for transactions.good_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.buyer_id
     *
     * @return the value of transactions.buyer_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.buyer_id
     *
     * @param buyerId the value for transactions.buyer_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.number
     *
     * @return the value of transactions.number
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.number
     *
     * @param number the value for transactions.number
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.status
     *
     * @return the value of transactions.status
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.status
     *
     * @param status the value for transactions.status
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.created_at
     *
     * @return the value of transactions.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.created_at
     *
     * @param createdAt the value for transactions.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.reason
     *
     * @return the value of transactions.reason
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.reason
     *
     * @param reason the value for transactions.reason
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}