package com.yuki.decmarket.model;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.privilege
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Byte privilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.tel
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.havecheckedemail
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Boolean havecheckedemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.baned
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Boolean baned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.privilege
     *
     * @return the value of users.privilege
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Byte getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.privilege
     *
     * @param privilege the value for users.privilege
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setPrivilege(Byte privilege) {
        this.privilege = privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.tel
     *
     * @return the value of users.tel
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.tel
     *
     * @param tel the value for users.tel
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.havecheckedemail
     *
     * @return the value of users.havecheckedemail
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Boolean getHavecheckedemail() {
        return havecheckedemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.havecheckedemail
     *
     * @param havecheckedemail the value for users.havecheckedemail
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setHavecheckedemail(Boolean havecheckedemail) {
        this.havecheckedemail = havecheckedemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.baned
     *
     * @return the value of users.baned
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Boolean getBaned() {
        return baned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.baned
     *
     * @param baned the value for users.baned
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setBaned(Boolean baned) {
        this.baned = baned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}