package com.yuki.decmarket.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.QQ
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.wechat
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.intro
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nickname
     *
     * @return the value of user_info.nickname
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nickname
     *
     * @param nickname the value for user_info.nickname
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.QQ
     *
     * @return the value of user_info.QQ
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.QQ
     *
     * @param qq the value for user_info.QQ
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.wechat
     *
     * @return the value of user_info.wechat
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.wechat
     *
     * @param wechat the value for user_info.wechat
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.created_at
     *
     * @return the value of user_info.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.created_at
     *
     * @param createdAt the value for user_info.created_at
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.intro
     *
     * @return the value of user_info.intro
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.intro
     *
     * @param intro the value for user_info.intro
     *
     * @mbggenerated Mon Jul 16 16:46:29 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }
}